#!/bin/bash

echo -n -e "\033]0;InstantWP SFTP\007"
osascript -e 'display dialog "The macOS SFTP client (Fugu) will now open." buttons {"OK"} default button "OK"'
cd "${0%/*}"
cd ../../..
open ./platform/osx/sftp/Fugu.app &
osascript -e 'tell application "Terminal" to close (every window whose name contains "InstantWP SFTP")' &
