#!/bin/bash

echo -n -e "\033]0;InstantWP Start Editor\007"
cd "${0%/*}"
cd ../../..
open ./config/iwp-osx.ini &
osascript -e 'tell application "Terminal" to close (every window whose name contains "InstantWP Start Editor")' &